### ISSUE TITLE
Metadata linkage created with invalid link to record

### ISSUE THREAD

**Issue by jonescc** [metadata101/iso19115-3#41] opened 2019-12-03 06:00 UTC
Running Geonetwork 3.8.2 but the code looks the same in develop (https://github.com/metadata101/iso19115-3/blob/3.5.x/src/main/plugin/iso19115-3/update-fixed-info.xsl#L173).

# To Reproduce
Create a new 19115-3 record
# What happens 
Metadata linkage element is added automatically with an invalid link to the record.  E.g. for a local install:
```
  <mdb:metadataLinkage>
    <cit:CI_OnlineResource xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0">
      <cit:linkage>
        <gco:CharacterString xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">
          http://localhost:8080/geonetwork/srv/eng//metadata/3347d207-5d0a-455f-bcc4-71dee1e6c4b3
        </gco:CharacterString>
      </cit:linkage>
      <cit:function>
        <cit:CI_OnLineFunctionCode codeListValue="completeMetadata" codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode"/>
      </cit:function>
    </cit:CI_OnlineResource>
  </mdb:metadataLinkage>
```

# What I expect to happen

A valid link to the record is used.  Looks to me like this was intended to be to http://localhost:8080/geonetwork/srv/eng/catalog.search#/metadata/3347d207-5d0a-455f-bcc4-71dee1e6c4b3 which would be good enough for us at the moment, but as per comments in the code - a configurable url template would be ideal.

**Comment by fxprunayre** [comment] 2019-12-03 19:10
> which would be good enough for us at the moment

Would a link pointing to the API 
http://localhost:8080/geonetwork/srv/api/records/3347d207-5d0a-455f-bcc4-71dee1e6c4b3
which uses the default formatter (which then propose a link to open the "portal") would be good for you ?

**Comment by fxprunayre** [comment] 2019-12-03 19:10
Also applies to 115-3:2018

**Comment by jonescc** [comment] 2019-12-03 20:14
Yes.  Using the default formatter would be better.

**Comment by jonescc** [comment] 2019-12-03 20:37
Looking at what that actually is, I notice that its hard coded to be the xsl-view.   Ideally we should be able to configure what the defaut formatter is?  Looks like we can do that for opening records from the search results (ui settings defaultUrl) although there is no support for editting that on the UI settings page at the moment except by using the JSON update option.

**Comment by jonescc** [comment] 2019-12-03 20:49
I'm actually having this problem with 115-3:2018.   Raised this issue in the wrong repository!

**Comment by jonescc** [comment] 2019-12-18 02:58
Upshot of all this is that yes linking to http://localhost:8080/geonetwork/srv/api/records/3347d207-5d0a-455f-bcc4-71dee1e6c4b3 would be OK, but we would then like that link to go to a configured view (not necessarily the xsl-view as we may have replaced that with something else - see other issues we are having with the proposed metadata citation where we may need to work around that in 3.8 by using a custom metadata view).

I can raise that as an issue in core-geonetwork though.

**Comment by fxprunayre** [comment] 2019-12-18 07:56
We need a way to configure the default formatter to use probably - not sure how?

Or we could redirect to  http://localhost:8080/geonetwork/srv/metadata/3347d207-5d0a-455f-bcc4-71dee1e6c4b3 which takes care of redirecting to a default formatter ?

**Comment by jonescc** [comment] 2019-12-19 01:23
That's the kind of link we want something that takes care of redirecting to the default formatter (formatter/defaultUrl in UI settings?) although I couldn't get that particular link (with our own uuid) to work.

**Comment by jonescc** [comment] 2020-01-31 06:29
Had a look at the suggested link in GN 3.10.0.   Its displaying a metadata citation proposal which is something we'd like to turn off.  There also doesn't appear to be an easy way to view the full record details.  Otherwise going to the normal defaul view would be fine.

**Comment by fxprunayre** [comment] 2020-01-31 06:47
> Its displaying a metadata citation proposal which is something we'd like to turn off.

Adding `&citation=false` in the admin > ui for the formatter should do it ?
https://github.com/geonetwork/core-geonetwork/commit/2f1091d814a6d3d6f8ec0b6f102c8809c5032eb2#diff-edd21e49392d7e5c427e2d2a2444ae99R19

**Comment by jonescc** [comment] 2020-01-31 07:15
This works:
http://localhost:8080/geonetwork/srv/metadata/b2eead80-716a-426f-bfe0-68c25c6d12fa?citation=false

But this doesn't?

![image](https://user-images.githubusercontent.com/1860215/73519599-a1761200-4455-11ea-8ca7-f14a3b8f3fba.png)

**Comment by jonescc** [comment] 2020-01-31 07:25
Also tried:
```
      "formatter": {
        "list": [
          {
            "label": "defaultView",
            "url": "/formatters/xsl-view?root=div&view=advanced&citation=false"
          },
          {
            "label": "full",
            "url": "/formatters/xsl-view?root=div&view=advanced&citation=false"
          },
          {
            "label": "Xml view",
            "url": "/formatters/xml_view"
          }
        ],
        "defaultUrl": "/formatters/xsl-view?root=div&view=advanced&citation=false"
```

Perhaps I'm missing something here.  Will have another look next week.

**Comment by fxprunayre** [comment] 2020-01-31 11:50
For me full view defined as `/formatters/xsl-view?root=div&view=advanced&citation=false` works fine. The URL is http://localhost:8080/geonetwork/srv/fre/catalog.search#/metadata/15579adc-5c9f-4762-9a9e-92ede8520f9d/formatters/xsl-view?root=div&view=advanced&citation=false
And no citation is displayed.
Can be a formatter cache issue ?

**Comment by jonescc** [comment] 2020-02-05 21:36
So some testing in 3.10.x with the formatter and browser caches cleared using a public record we have there (8159f519-8c51-49f7-9fd0-c22331b2806b) and full view configured in ui settings as follows: 

```
      "formatter": {
        "list": [
          {
            "label": "defaultView",
            "url": ""
          },
          {
            "label": "full",
            "url": "/formatters/xsl-view?root=div&view=advanced&citation=false"
          },
          {
            "label": "Xml view",
            "url": "/formatters/xml_view"
          }
        ],
        "defaultUrl": ""
```
#### Suggested url

http://localhost:8080/geonetwork/srv/eng/catalog.search#/metadata/8159f519-8c51-49f7-9fd0-c22331b2806b/formatters/xsl-view?root=div&view=advanced&citation=false

Shows no content

![image](https://user-images.githubusercontent.com/1860215/73883979-08ae1f00-48b9-11ea-9fc4-778f7d41b1b9.png)

#### api/records

http://localhost:8080/geonetwork/srv/api/records/8159f519-8c51-49f7-9fd0-c22331b2806b 

Better but displays citation which we'd like to turn off.   Also looks like the sidebar has been included at the bottom of the page - would be better where it normally is or left out altogether.  Clicking on the catalogue and search links at the top of the page take you to a sign in page?

![image](https://user-images.githubusercontent.com/1860215/73884518-22039b00-48ba-11ea-80be-3a079365df9d.png)

#### api/records - citation=false

http://localhost:8080/geonetwork/srv/api/records/8159f519-8c51-49f7-9fd0-c22331b2806b?citation=false

Better - citation is not displayed other issues above still present.   Problem is that I don't think you would want this link put into the metadata in the core plugin?  We were looking at a core solution for turning off the proposed citation - otherwise we'd have to modify the schema fixups/provide forked plugins to our contributors creating installation/upgrade/management problems.

#### originally suggested link

http://localhost:8080/geonetwork/srv/eng/catalog.search#/metadata/8159f519-8c51-49f7-9fd0-c22331b2806b

Goes to default page configured in UI settings - no proposed metadata citation - options to display full record etc.

What was the problem with this option?  Looks like there's a bit of work to get the other options working well and not displaying metadata citations

![image](https://user-images.githubusercontent.com/1860215/73885349-bae6e600-48bb-11ea-9885-38bddcae3ca2.png)

**Comment by jonescc** [comment] 2020-02-20 00:40
So looking through other code/pull requests I can see that you're looking to make the geonetwork/srv/api/records/8159f519-8c51-49f7-9fd0-c22331b2806b endpoint the default landing page for records.  As noted above, there are some issues with this page, (and in particular for us being able to configure it to turn the proposed citation off), but if the intention is to fix issues with this page and ideally for us to be able to configure the page to turn off  the proposed metdata citation then yes the landing page url for the record is what we should be using.

**Comment by fxprunayre** [comment] 2020-02-20 17:20
For 3.10.1, we could turn off citation by default also. If only Ifremer is using it, I can enable it for them on next merge. Layout issue (right column below main one) is usually due to self closing tag which cause issue on Chrome. I will try to have a look which element is concerned. It may be easier to reproduce if you can share the metadata record ?

**Comment by jonescc** [comment] 2020-02-20 21:03
Just tried this again in master and the sidebar is displaying correctly now.  So that sounds good.  I really appreciate your help here.  Thanks Francois!

**Comment by jonescc** [comment] 2020-02-20 22:11
![image](https://user-images.githubusercontent.com/1860215/74983455-24edb680-548a-11ea-92c3-7f74b8eeefcd.png)

**Comment by jonescc** [comment] 2020-02-26 06:27
Hi Francois, this is still an issue for us in 3.10.1.  Wondering what to do about it as this is something we'd like to get resolved if possible.  Some options

- disable citation proposal in core until a way of configuring this for api/records/{{uuid}} is implemented - use api/records/{{uuid}} in the linkage
- add a configuration option in UI Settings for api/records/{{uuid}} to be able to configure the view to display as per  the defaultUrl for viewing metadata records, use api/records/{{uuid}} in the metadataLinkage and modify api/records to use the UI Setting (default would be xsl-view as per current hardcoded setting)
- add configurable url to 19115-3 schema plugin so that the metadataLinkage url could be derived from the metadata and environment parameters (DOI's, custom views or other external links)

I'm obviously happy with the first option.  I think the second option is required for using the api/records/{{uuid}} endpoint regardless of what url is used in the metadata linkage and the last option is a nice enhancement which we probably won't have time to do - needs some thought as we would like this to be easily configured without requiring forking of the plugin.

**Comment by fxprunayre** [comment] 2020-02-26 06:37
> I'm obviously happy with the first option

Fine for me to turn it off by default.

Following discussions around here on this, it looks like we should only provide the citation proposal in some particular cases - ie. mainly once a DOI is created because then it make sense to cite a dataset. Beforehand it probably does not really make sense. Not so many people are creating DOI (here mainly Ifremer, BRGM). So maybe that could be the default rule - "display citation only if a linkage with DOI protocol is set" ? or we could also simply turn it off.

**Comment by jonescc** [comment] 2020-02-26 22:48
Our metadata expert is away at the moment, but I'm pretty sure even if we were using DOI's we wouldn't want the citation proposal as it is.   Would a custom view be the best way to handle rules around when to display the proposal and what should be in it?  That's what we would have used to turn it off except the api/records endpoint would still use the hard coded xsl-view  (we would just import the xsl-view and override the getMetadataCitationPorposal template to not return anything).   There's already a mechanism for importing formatters (we don't use this we use maven overlay's to add custom views but its a customisation/maintenance friendly option). 

For the moment I'll switch the citation proposal off by default until this is sorted out.

**Closed as completed** 2020-03-06 07:00 UTC
